#!/usr/bin/env python
'''
pycallgraph
This script is the command line interface to the pycallgraph Python library.

See https://github.com/Lewiscowles1986/py-call-graph for more information.
'''
import os
import sys

# Inject the current working directory so the target script's imports resolve.
sys.path.insert(0, os.getcwd())

from pycallgraph.cli import main  # noqa: E402


if __name__ == '__main__':
    sys.exit(main())
