name: CI

on:
  pull_request:
  push:
    branches:    
      - main
  schedule:
    - cron: 0 6 1 * *
  workflow_dispatch:

permissions:
  contents: read

jobs:
  setup:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.5
      uses: actions/setup-python@v3
      with:
        python-version: "3.5.10"
        cache: 'pip'
        cache-dependency-path: |
          setup.py
          requirements/**.txt
    - name: Install dependencies
      run: |
        python -m pip install -r requirements/development.txt
